import pytest
from packages.tradeflow.indicator_calculator import IndicatorCalculator
from packages.tradeflow.types import InstrumentCategoryType

def test_canonical_indicator_names():
    """
    Verifies the exact keys generated by IndicatorCalculator for the 
    'dummy-reference-strategy' to establish a ground truth for strategy code.
    """
    # This matches the 'dummy-reference-strategy' seeded in seed_strategy_indicators.py
    config = [
        { "indicator": "ema-5", "InstrumentType": "SPOT" },
        { "indicator": "sma-50", "InstrumentType": "SPOT" },
        { "indicator": "rsi-14", "InstrumentType": "SPOT" },
        { "indicator": "atr-14", "InstrumentType": "SPOT" },
        { "indicator": "macd-12-26-9", "InstrumentType": "SPOT" },
        { "indicator": "supertrend-10-3", "InstrumentType": "SPOT" },
        { "indicator": "bbands-20-2", "InstrumentType": "SPOT" },
        { "indicator": "vwap", "InstrumentType": "SPOT" },
        { "indicator": "obv", "InstrumentType": "SPOT" },
        { "indicator": "price", "InstrumentType": "SPOT" }
    ]
    
    calc = IndicatorCalculator(indicators_config=config, max_window_size=100)
    
    # Add enough candles for all indicators
    for i in range(100):
        calc.add_candle(
            {'t': 1000 + i*60, 'o': 100+i, 'h': 105+i, 'l': 95+i, 'c': 100+i, 'v': 1000}, 
            instrument_category=InstrumentCategoryType.SPOT,
            instrument_id=26000
        )
    
    res = calc.latest_results[26000]
    
    # ASSERT EXACT KEYS
    # 1. EMA
    assert "nifty-ema-5" in res
    assert "nifty-ema-5-prev" in res
    
    # 2. SMA
    assert "nifty-sma-50" in res
    
    # 3. RSI
    assert "nifty-rsi-14" in res
    
    # 4. ATR
    assert "nifty-atr-14" in res
    
    # 5. MACD
    assert "nifty-macd-12-26-9" in res
    assert "nifty-macd-12-26-9-signal" in res
    assert "nifty-macd-12-26-9-hist" in res
    
    # 6. Supertrend
    assert "nifty-supertrend-10-3" in res
    assert "nifty-supertrend-10-3-dir" in res
    
    # 7. Bollinger Bands
    assert "nifty-bbands-20-2-upper" in res
    assert "nifty-bbands-20-2-middle" in res
    assert "nifty-bbands-20-2-lower" in res
    
    # 8. VWAP / OBV / Price
    assert "nifty-vwap" in res
    assert "nifty-obv" in res
    assert "nifty-price" in res

def test_explicit_indicator_id_names():
    """
    Verifies that if indicatorId is provided (as in test seeding), it overrides the shorthand.
    """
    config = [
        { "indicatorId": "ema5", "indicator": "ema-5", "InstrumentType": "SPOT" }
    ]
    calc = IndicatorCalculator(indicators_config=config, max_window_size=10)
    res = calc.add_candle({'t': 1000, 'o': 100, 'h': 100, 'l': 100, 'c': 100, 'v': 100}, instrument_id=26000)
    
    assert "nifty-ema5" in res
    assert "nifty-ema-5" not in res
